KTB-7-learnWord
Evgeniy-mas/KotlinTelegramBot pull request #1
Opened 2024-11-06 08:18 UTC by Evgeniy-mas

2024-11-06 13:33 UTC, Evgeniy-mas commented
Из-за проблем пересоздал репозиторий KTB. Перенес переменные статистики в блок when.

2024-11-06 13:36 UTC, Evgeniy-mas commented
Были замечания в данном уроке, что не правильно беру варианты translate и original. Переделал, правда не понял правильно ли=)

2024-11-07 04:56 UTC, danelyan requested changes

2024-11-07 04:56 UTC, danelyan commented on src/main/kotlin/KotlinTelegramBot/Main.kt
> +                val notLearnedList = dictionary.map { it.correctAnswersCount }
тут следует сразу получить список невыученных слов, ты же их просто маппишь в цифры

2024-11-07 04:56 UTC, danelyan commented on src/main/kotlin/KotlinTelegramBot/Main.kt
> +                if (notLearnedList.all { it >= CORRECT_ANSWERS }) {
Тут достаточно проверить что список notLearnedList не пуст. Пуст - значит все слова выучены

2024-11-07 04:56 UTC, danelyan commented on src/main/kotlin/KotlinTelegramBot/Main.kt
> +                println()
перенос строки лучше добавить в один из выводов которые уже делаешь - в конце или начале

2024-11-07 04:56 UTC, danelyan commented on src/main/kotlin/KotlinTelegramBot/Main.kt
> +                val questionWords = shuffledWords.mapIndexed { index, word3 ->
а почему `word3`?

2024-11-07 11:37 UTC, Evgeniy-mas commented
Поправил.

2024-11-10 12:20 UTC, dzenonce approved these changes

2024-11-10 13:11 UTC, merged