KTB-14-Regex
Evgeniy-mas/KotlinTelegramBot pull request #11
Opened 2024-11-22 09:15 UTC by Evgeniy-mas

2024-11-22 17:03 UTC, dzenonce requested changes

2024-11-22 17:03 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/Telegram.kt
> +        val updateIdRegex: Regex = "\"update_id\":(\\d+)".toRegex()
Regex лучше записать в переменную за пределами while. Мы стараемся не пересоздавать переменные лишний раз.

2024-11-22 17:03 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/Telegram.kt
> +        val updateString = matchResultId?.groups?.get(1)?.value
Давай делать `continue` если у нас null через элвис-оператор

2024-11-22 17:03 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/Telegram.kt
> +        if (updateString != null) {
Эту проверку можно убрать в таком случае

2024-11-24 12:13 UTC, dzenonce requested changes
Данный пулл реквест невозможно смержить из-за образовавшихся конфликтов. Посмотри этот урок, там наглядно показано, как разрезолвить этот конфликт. Ссылка с таймкодом https://youtu.be/vJdKYa49SqY?si=oV-vXh2sZQXoON1b&t=393

2024-11-25 09:14 UTC, Evgeniy-mas commented
Исправил.

2024-11-25 19:00 UTC, dzenonce approved these changes
Да, все отлично!

2024-11-26 09:00 UTC, merged