KTB-17-statistic-bot
Evgeniy-mas/KotlinTelegramBot pull request #14
Opened 2024-12-02 08:00 UTC by Evgeniy-mas

2024-12-02 08:02 UTC, Evgeniy-mas commented
переменные statistics_clicked и learn_words_clicked вынесены в константы в файле telegramBotService.

2024-12-02 18:45 UTC, dzenonce requested changes

2024-12-02 18:45 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/Telegram.kt
> +    val trainer = LearnWordsTrainer().getStatistics()
Лучше создавать экземпляр тренера и прокидывать его где он нужен, чтобы вызывать методы

2024-12-03 17:38 UTC, dzenonce approved these changes
Да, так лучше

2024-12-04 08:16 UTC, merged