KTB-18-learnedFunc
Evgeniy-mas/KotlinTelegramBot pull request #15
Opened 2024-12-09 07:18 UTC by Evgeniy-mas

2024-12-09 07:19 UTC, Evgeniy-mas commented
Что то я тут намудрил. Получение индекса с константой  CALLBACK_DATA_ANSWER_PREFIX скорее всего не правильно.

2024-12-09 21:01 UTC, dzenonce requested changes

2024-12-09 21:01 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/TelegramBotService.kt
> +             "text": "${question.variants.map { it.translate }[0]}",
обрати внимание, что `{ "text": "${question.variants[3].translate}", "callback_data": "$CALLBACK_DATA_ANSWER_PREFIX${variants[3]}" }` повторяется на каждый variant из `question.variants` и соединяется запятой. Мы можем сделать данный код компактнее и универсальнее.

Для этого нам надо каждый `variant` смапить в строку, а вместо цифры использовать индекс:

val variantsString = question.variants
    .mapIndexed { index, word -> 
        """
            {
                "text": "${word.translate}",
                "callback_data": "$CALLBACK_DATA_ANSWER_PREFIX${index}" 
            }
        """.trimIndent() 
    }
    .joinToString(separator = ",")

2024-12-11 08:33 UTC, Evgeniy-mas commented
Чет я запутался. А как мне внедрить  смапинную переменную в inline кнопки? или их надо прям в mapIndex вставлять к у меня в примере.

2024-12-11 20:41 UTC, dzenonce commented
> Чет я запутался. А как мне внедрить смапинную переменную в inline кнопки? или их надо прям в mapIndex вставлять к у меня в примере.

Ты формируешь строку с кнопками и подставляешь ее в запрос
```

val variantsString = question.variants
.mapIndexed { index, word ->
"""
{
"text": "${word.translate}",
"callback_data": "$CALLBACK_DATA_ANSWER_PREFIX${index}"
}
""".trimIndent()
}
.joinToString(separator = ",")
```

2024-12-11 20:43 UTC, dzenonce requested changes
Примерно так должно получится
```
val sendQuestionBody = """
{
    "chat_id": $chatId,
    "text": "${question.correctAnswer.original}",
    "reply_markup": {
        "inline_keyboard": [
            [
                $variantsString,
                {
                    "text": "Меню",
                    "callback_data": "$MENU"
                }
            ]
        ]
    }
}
""".trimIndent()`
```

2024-12-12 08:29 UTC, Evgeniy-mas commented
Да заработало. Удобно, что прям так можно подставить кнопки в Json.

2024-12-12 18:12 UTC, dzenonce approved these changes

2024-12-13 07:24 UTC, merged