KTB-04-parsingFile
Evgeniy-mas/KotlinTelegramBot pull request #2
Opened 2024-10-26 12:07 UTC by Evgeniy-mas

2024-10-27 10:51 UTC, dzenonce requested changes

2024-10-27 10:51 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/KTB-04-parsingFile.kt
> +            splitLines[2].toIntOrNull() ?: 0
Оператор `[2]` можно заменить вызовом метода `get()` - это будет эквивалентная операция. 
А можно использовать `getOrNull()` - которая в случае ошибки обращения по индексу возвратит `null`: `val correctAnswer: Int = splitLines.getOrNull(2)?.toIntOrNull() ?: 0`.

Тогда код будет еще короче

2024-10-28 06:29 UTC, Evgeniy-mas commented
Поправил с использованием getOrNull.

2024-10-28 16:20 UTC, dzenonce approved these changes

2024-10-29 07:03 UTC, merged