KTB-10-test
Evgeniy-mas/KotlinTelegramBot pull request #6
Opened 2024-11-15 06:42 UTC by Evgeniy-mas

2024-11-15 19:55 UTC, dzenonce requested changes

2024-11-15 19:55 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/LearnWordTrainer.kt
>      private fun saveDictionary(dictionary: MutableList<Word>) {
В данном методе есть проблема, при первом запуске и изучении слов все хорошо, но если этот метод отработал и перезаписал файл, слова записываются в одну строку, из-за чего, при следующем запуске будет только одно слово для изучения
Исправляется это довольно просто, добавлением символа переноса в сформированную строку
`file.appendText("${word.original}|${word.translate}|${word.correctAnswersCount}\n")`

2024-11-18 05:57 UTC, Evgeniy-mas commented
Поправил.

2024-11-18 15:23 UTC, dzenonce approved these changes

2024-11-18 15:29 UTC, dzenonce approved these changes

2024-11-19 05:41 UTC, merged