KTB-07-learnWord
Evgeniy-mas/KotlinTelegramBot pull request #6
Opened 2024-10-31 13:44 UTC by Evgeniy-mas

2024-10-31 13:49 UTC, Evgeniy-mas commented
Переименовал основной файл в main. Никак не пойму, как выводить слова которые надо учить по очереди, чтоб не повторялись подряд.    Переменная questionWords.

2024-10-31 18:21 UTC, dzenonce requested changes

2024-10-31 18:21 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/main.kt
> +                val questionWords = dictionary.filter {
Давай возьмем `questionWords` и с помощью `mapIndexed {}` и `joinToString` получим строку с вариантами ответа. 

В `joinToString` используем: параметр `separator` для переноса строки, `prefix` непосредственно для оригинального слова на английском, а  `postfix` переносы строки и пункт меню для выхода.

2024-11-02 10:16 UTC, Evgeniy-mas commented
Переделал с mapIndexed.

2024-11-02 15:30 UTC, dzenonce requested changes

2024-11-02 15:30 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/main.kt
> +                val original = dictionary.filter {
Обрати внимание, мы должны сначала брать из списка с не выученными словами 4 перемешенных слова и уже из него получать слова для изучения и перевод, к тому же, отображать нужно всего 4 слова)
Посмотри в сторону методов `take` и `shuffled`

2024-11-05 06:01 UTC, Evgeniy-mas commented
Добавил take и shuffled.

2024-11-05 18:50 UTC, dzenonce requested changes
Сейчас давай поправим по комментам, и в следующем pr нужно оставить только файл main с актуальным кодом и модель данных word

Еще по поводу нейминга веток, нужно двигаться в том-же флоу как и ранее, на каждую задачу, своя ветка с префиксом проекта и номером задачи с кратким описанием по задаче
То, что ты создал ВЕТКУ с неймингом main довольно плохо, по хорошему нужно ее закрыть и создать ветку с нормальным названием по нашему флоу, в которую запушить все изменения

2024-11-05 18:50 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/main.kt
> +                val questionWords = translate.mapIndexed { index, word ->
Данное решение не соответствует ТЗ
Нам нужно брать 4 рандомных слова из словаря и отображать их, также слово для перевода нужно брать из этого же набора из 4-х слов, чтобы было соответствие вариантам ответа

2024-11-05 18:50 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/main.kt
> +    val totalCount2 = dictionary.size
Для чего здесь эта, wordsLearned. percent переменные, давай выполнять все действия локально при необходимости внутри when

2024-11-05 18:50 UTC, dzenonce commented on src/main/kotlin/kotlinTelegramBot/main.kt
> +    val percent = (wordsLearned.toDouble() / totalCount2) * 100
пользователь может не зайти в меню статистики, а ты уже нагрузил ему проц

2024-11-06 07:39 UTC, closed without merging